### ISSUE TITLE
Sponsorship information & application page *sponsor.html*

### ISSUE THREAD

**Issue by wanseob** [ethcon-kr/ethcon.kr#11]
1. Sponsorship package
    - Please refer the sponsorship [deck](https://docs.google.com/presentation/d/1QwE0iBCH7-_bW1LGhgzlTnhhfMjTb8elfWncpqv4IkI/edit?usp=sharing)

2. Application form
    - Please use formspree.io like in `proposal.html`
    - Recipient should be sponsor@ethcon.kr

**Comment by HeesungB** [comment]
Korean : [deck](https://docs.google.com/presentation/d/1GVivjJlPjXZQFcOUqUdG5CSMmODQ5aJ5bjLAGROOaL8/edit#slide=id.g550e6cdd84_0_27)

English : [deck](https://docs.google.com/presentation/d/1QwE0iBCH7-_bW1LGhgzlTnhhfMjTb8elfWncpqv4IkI/edit)

**Comment by wanseob** [comment]
How about using symbols?

TIER 1 : ₩10,000k (≒ $ 8,845) [2 AVAILABLE]
TIER 2 : ₩5,000k (≒ $ 4,422) [4 AVAILABLE]
TIER 3 : ₩2,000k (≒ $ 1,739) [10 AVAILABLE]

===== 

TIER 1 : 10,000,000 KRW(≒ 8,845 USD) [2 AVAILABLE]
TIER 2 : 5,000,000 KRW(≒ 4,422 USD) [4 AVAILABLE]
TIER 3 : 2,000,000 KRW(≒ 1,739 USD) [10 AVAILABLE]

**Comment by HeesungB** [comment]
@wanseob  I'll update that
